### ISSUE TITLE
any chance of getting that for indigo ?

### ISSUE THREAD

**Issue by vrabaud** [ros-visualization/oculus_rviz_plugins#20]
Thx !

**Comment by dgossow** [comment]
I haven't been actively working on this for quite a while. Someone would need to pick up the baton.

**Comment by vrabaud** [comment]
just a tag and a release is all we need :p

**Comment by dgossow** [comment]
I don't even have a machine with ROS on it and am really out of the picture regarding the whole release procedure, which will make this more complicated for me. If it's little work for you, could you just do it?

Also, be aware that this likely won't work with the DK2, so I don't know how useful it is at this point.

**Comment by UltronDestroyer** [comment]
I'll take this over.

**Comment by dgossow** [comment]
Thanks!

**Comment by clalancette** [comment]
Closing to archive this repository.
