### ISSUE TITLE
[Request] Ownership of package

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-visualization/oculus_rviz_plugins#21]
Required for release into Indigo, as mentioned in other issue, Dgossow would like to relinquish ownership

**Comment by wjwwood** [comment]
> as mentioned in other issue

Please link the issue when you reference it: https://github.com/ros-visualization/oculus_rviz_plugins/issues/20#issuecomment-67182886

I can add you to the repository, you'll need to update the `package.xml` to include yourself as a maintainer. Make sure to move existing maintainers to an `<author>` tag.

**Comment by UltronDestroyer** [comment]
I can do that @wjwwood

**Comment by http404error** [comment]
@TheDash So you're inheriting this package? I was actually going to do it myself if no one else was going to, but I suspect that you're better qualified. Do you have any plans to work on DK2 support? There's been word of several other parties working on that, but I haven't heard anything in quite some time, and we were about ready to dig into that ourselves.

**Comment by UltronDestroyer** [comment]
I was only going to release it into Indigo. I do not intend to develop on
it. If you'd like, you can submit any work as a pull request and we can
merge it in once its ready.

On Wed, Feb 11, 2015 at 1:05 PM, Benjamin Arvey notifications@github.com
wrote:

> @TheDash https://github.com/TheDash So you're inheriting this package?
> I was actually going to do it myself if no one else was going to, but I
> suspect that you're better qualified. Do you have any plans to work on DK2
> support? There's been word of several other parties working on that, but I
> haven't heard anything in quite some time, and we were about ready to dig
> into that ourselves.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-visualization/oculus_rviz_plugins/issues/21#issuecomment-73942397
> .

## 

Devon Ash
<a href="http://ca.linkedin.com/pub/devon-ash/48/478/981"
style="text-decoration:none;"><span style="font: 80% Arial,sans-serif;
color:#0783B6;"><img src="
https://static.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png"
width="20" height="15" alt="View Devon Ash's LinkedIn profile"
style="vertical-align:middle" border="0">View Devon Ash's profile</span></a>

**Comment by http404error** [comment]
Alright, thanks.

**Comment by clalancette** [comment]
Closing to archive this repository.
